---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-token
  namespace: cloudflare-tunnel-dev
spec:
  encryptedData:
    tunnel-token: AgAVzhLwFAGosKyg7XvUdQS7fwiCRveHsunhnlCCnPwJm7PqJB7Vj6ejZTd+MPDcM8oZeemNbi5+NAhpQon78g6E5me0MTrjUp0hcwBIXK6m3H4hLVoxrtIIsJW/gCbOuVlFfDcrTpt95b1zGVu+8Tlkt5DSMcZTIHL+56E6hwOZ+cpe60g9mwYvzrTb5eoAnRUuo3dZfnl648G2KngZ7mJTx5Dcihvhf/hFpYD3QA6hF9kA9+1O5WflfEobEw162kljoBZyi5Ere0apZp77RZAPqBC7u0eE+h7gFhw1wsLGVCmSsprw/2FfuPXkOz2qkG+CGgK0qpji7v/hyCcwl9h/tZ0v2Jn5omJpvW/CBzmEZqrxmp62gbAv7itAAtiA7+jBbjPFN+5mfnVj72pf3b609RV5yvJMzohKvIme5deWhvZEpfDbw6F4Zy8m3z73p5RNiJnETUs3f11RW1LATJYMe8OiwlGlcJCfJvTnO72EgNrWEfGF/n7PAI8VUnbDjrggUvkPX5h4gDlDjZgtqXu39Kr0p9y/IdOJ+gsdmU013MWEUo40LcBqrqqYpGoIAvwF/rSfPBvmSku40SKrC/MTKKx50F9U51RT/aZiOuJpD1sTu7J3CLa6KLDs7hoXbto1VCjqLs2Vz8on21pd8U9QrKIh9rvWlrH7vKbjaHQZq9nEIGE1w5+RvzILyAwliGpvZVCOnI3I9HFA9idn/YcrkEDmuZr4mydA02SMtxBU8xR+VhgiZUy2t1XwLtcjnBG/T2X3mfTAlT83snOytO3ZvxrtaepeesbOucz3+qN4CIwEBzjMXUoPMTFJSJmzCaKOVXyPWwFbKJHENZseX+YKfA/KsVrT6qo1LZEXKqFMErhlCVKmADPicP9DyBMaeYBwAh4MqaW2XrBQewTDmJjtlOKTVaoNoF1sx6Q+5fsErn2G+Sw=
  template:
    metadata:
      name: cloudflared-token
      namespace: cloudflare-tunnel-dev
