---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-token
  namespace: cloudflare-tunnel-dev
spec:
  encryptedData:
    tunnel-token: AgBXK1N2JAd0EnHPltE5ItTeQfhbuw5HOsNmP9V2CO7d9Wq9VOZw/szEM2yzng/KKI8/Y5G4PdbRB0Bi5QKmVOWqY0OFJeNlx9WsV+omFLUPaVlXyDpqrxUo+zldcwuLYERWT6UCQTqXT9ny0Zno7WjyMOzbiHOdcMa651e89L64/vvbaaNnjvGcvh6MVrj0FCOT9cBPGYDkUGUelOyY30H8C/ujla9QV3TI97yB/sbxUKIH0HasSQL1uisZS/hbXqGBA38jVkamivTJDAAbkm3xd1UOr1w4SAsaXmY2GAPo7b/hsxQUQ4hmkfY1i8Q8GTAk4ZvBsvl5zg/cO4agW1OriBXeTgzW7ioijalYTSZaUAbRuPhXIrx8yVGF+J3h98fcjesRYpf4TEcblPNXIWlX0yfzD6TZvEpAt4lCvZPvNnedvfqXVzJfQL61EZ2KTDh+mWqosZrsvzcL0kHiT+xZSFLMAVQ6oZLWsiHoEaUutVPomOr3nJTnBCKSlRZ18QtI0DEV4gQi9XDijvR/37quFeNStmTR2RU3Vwko95N4Bp+9pPUmlqRFUA+EVOQFoyn4FeAQes6pHFCwYC/LIuaAGQe587EX+T/fv40VltqpjEH476PPdIYXFIOZqku1n2dBbf6RKZLcy9/2EIp9VuDerAPShX/jXgwIxY60dpi+N3kwd88eiJPRV5X8STmIcbZH7XK2c4oJUGcltfUmWIuga2Z+zgLgzV3bWob9+FF4esNDWlN7XYnEu5po8kiXc8ZA4scLpRkbVJojqcHuHDDi7P3za7y+L3rExZtHKsAaiqohETdUhFd6wkPhYqA1GuIMHnQfQjNDYQMiA7INWMeea/Dmu9MFBKEG97jSDWFzwGrPJdjkTF3Qgfyy/ekdvz28rfe4pMf4/m2jOInPaUoccYQW7Q4onJ7ycQsGbsHyF7kAXPI=
  template:
    metadata:
      name: cloudflared-token
      namespace: cloudflare-tunnel-dev
