---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-token
  namespace: cloudflare-tunnel-dev
spec:
  encryptedData:
    tunnel-token: AgCTF3z/0M9OAZXAa00fVpnkco3CExM/oGKExPl/7c4vSWveI36u6Mizs8Q6tOddp3ejR6QRkQQGVpPoXEBPmNLjWx+9onb7GtaqoBuqrGvzP0MXIxP9R9VcxcKj4qNN6vJfGA11XUQRyy46DvGhm2L66eKLzn86pzqVEwAKXO7jPLdIlyTlHwETX3zyAw6iRbx50WitZpqgOqXALZ1PaO5E8XYL6TjtAkQrSqrbKyLw8e1MyEvxQsl/tFTX9WzUY6QrCTVAagrv1vDcURr4a1WpJG4ODxUGpI5ogskRIJ4D28tBK1FWGv26p0LjMdMLbchzHEAbHsb28nPCmfENIPVvmCo54fKbJQKUQpcetz7ac6PElOkLYhTLhE4KkYGVr2YIF/r0mvIC1lTSuHhcdb1UMIkTgMuN8klyV2gMIz1/PezoS/JI5Xiku2xix5viAdEIjA5UmOgUgYvbVs+ss1JMMo7HhlqjtjIXEBgRrDzOOxMpebPFUd6DKxNKbWoDbe3Q/ApxjSXqOoNw9HL5hd6HikyGMbaJzfDSbKTkXvvT38fVg4Ih3+CPRVR7QzamzkpHB3kHotAssXPebHBRzlGpPZKd6n869VQ5NQkaa+BOY5bW/PpKPcVFTG5nEB62Rr+Tu1HuofanVeN4lKwvs4mb2ToxNXz6gstIFnI52gkvgv8c/CS4QiG51ZFLMlCH1LonPIv9Z98N/Z/etsM8MV0v/9Imd3mjzZqDL5AfWzZ+6Ivw1KYcKWELtZcn0y2oemJmnduDu6h2ISBdmUX+QC5h0fnDekfidyWPu2/qAE2V15XqpqAOVGCNwfh4/1eHYX8Uv2trB3qRUReN8kelvtMxzjDGDAXndMACAwguACls3tzbFIn46MqZM0gCo9mcJcpN0FdjHVKmiF5jyu5zFArZ+XmSlTzjkwqxoBONpcgLoU59BJ4=
  template:
    metadata:
      name: cloudflared-token
      namespace: cloudflare-tunnel-dev
