---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-token
  namespace: cloudflare-tunnel-dev
spec:
  encryptedData:
    tunnel-token: AgCokyu8Q1KHZis7z+lHSrkP6m0AoqLafjORoEhL9+xf1aNQwbwgtBh/enko+owrnzuhZrcljQWEFKweJ0HZxEAV88akrfKYLZpUOZmOBsiXppAK46PwWaS4cOoUbzrCHv7C3pZ6NG+qHxSBsr4s2DVSXGKbcy6V1Br1oEJl46ZBnfL7nEWrLcx+pvB7FSS40SGbtHoIKYmqIt4z1NUGqHh7WYmrl26Yu+tMytwfz/96MLm5M7yf+N68Ogs0gg0BeHBiVQXBczXGwY8ZNTDwoigMDiBLm5agMZGPXE1wU0IGOSwygjmQCCL6ZYJ5erd6HQXbkURsoiLntcG6WGeSQSJVFi3tc+Xm3CJqbC+b3hSfFDmXuFPgH2SKQD+NmRtB4pVSLZ0DIRLVGVuTdwSUF8larNxFn01Z7mt3ScIUSx2LmeRfHgsVSZhNtNMsDuaIs+LUzalerkpg9neZQg+gWu+FELnzE59rn+fe0dpXCaEvHbmYkAq01ceXFUmzK6jWL39Y1UBHiRIVXfbzsh6xx8xTmdow2LjFGGRsHcfsp/0mRdNGtOIC2a6Djp3fgq/jDGE4l2AvPPU02Ar+eslgF3DcenoN7SG5ZPqcNdvb+On8387IVIzzuKbEtb30XLoUZ/o4rF65+NeE67eB/LaEAR28OCxboXzN+KD44w+FlGxNB5RvEIhIt9Jj2ymk7GeJI4aEWDaIw1D+SaG1zjyOU2wn4Md0pNHAjk4bQGgxivgg0PN+elPgt9KBToLfuv2LBPlMd0ep0nYLEUBZ+NLEbxHdAwXZiZAEbxACpjFK9ltTH6oJl/1cAGx+u4h3Zs0ARZQ74KRw1/SjqeI0NvuqeKVorsys3kl03Jm9YH6G81egtQ7ZwB3mxiMPCtjyOtxfJEs9r0xRuNm2q7ZThjVhSK1tdLK2uZKQyPC/b/UIFul3S7FhV+o=
  template:
    metadata:
      name: cloudflared-token
      namespace: cloudflare-tunnel-dev
