---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-token
  namespace: cloudflare-tunnel-dev
spec:
  encryptedData:
    tunnel-token: AgB/TEimi24vLwyYAV9xHb0EFlcFct3glqmnh8Mq3Y/HDYzOaFn0koKTMPTiBSA2zecS5oZo9/KrulXvrvIBV/g9PIfzflF13GX9HmDf9tSsaFEQq8LCDzBWOdOJT19QacuaYZ9SVlKAjrak7B0chehxBWn1zMD4gF01IE+YJdELN+tk8gf0ffEOeAeiilNp0u/eNfhBICa1XoYAnOf1HfyIdyTaZgWhciEOqNP5rzxPICg8mLmggZtS0JNw3z1XiUd48nuwObDDpMaKLlv90Hq/X7JEuyM+x4xQeuaeg1qxUsaOuoZh4h4xhHgaECgqA2n5jYdsJBoXEh3efGsf2mhk9DWRkB9ApozTcOw1ARH8obF4m75DWYWKKtmxfSFHypFnNU4egxF6E1z8Kkl7NfNWr9zc/wqAaQUJUjDTcdWamQVGaXviMAudhJbq2+sM+RJxL10h8nfFtojT3r3Dmv9Eb4CzQ0lBMmxJ2x4KZWWfMwmYk4VF3kS4pGdNcuLnd5Az/OuLkAZ4rUQqp8QN4kh8LMIevFPkH9qnMmzc9CpiDMdSWEkE3Yl1luMfN7ua/8Mn5CRMhyOPabHFniOxa3Q9XcH9g4u181foY7h++RI3dc9cWTTr5RdqfG6U5lWAYowOfGPMjaQ/jnUn+8ooar5oWe0FwgYe8yJsyW94vdY+TGVO517WSMJ8HUqKcsQP9wOBLAOhOwZBkpDnzBAgYsR4cpSYzE3kB93UZrz87bSDPuxEmug1RYF3i+KnU34hRZZC/P5cnZEM1K2ma/pCcGwmjRmKVIyrJ4UhK95GM1PPYqF7R/1BMxGsmJnxwlzeGVHvMnjwubInmb+C47g2o/U1RBfbo93OpBn8qUUmyOGZ+5yxn3LLqgs8kiGAzMvnzl5/7a134eZM5RGDAUXXoOr8Px1matBnCfeT+3bYrUyNEFFJEg4=
  template:
    metadata:
      name: cloudflared-token
      namespace: cloudflare-tunnel-dev
