---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-token
  namespace: cloudflare-tunnel-dev
spec:
  encryptedData:
    tunnel-token: AgCW8AKv1qYvwN+kfRxpTYS12iKPD9JWRckzsLI/ZW0TmCuqqnrRXjVU2L9gDD45+IyRuaEqMOlox3hpKRlpYU3oWzNuJSI2HbTPtpL1PnuPci4JR1783oZ1odzfQtst50mf8vNMOzrsl0YyU+LKrmE3xlQSH73VuiZ7vtqw9UY4IjAPUppoX/fDO0OVcDuUOtnrFTvWvS2wCRYOULv/UOrF0CdAJkLjD7RcLSpDqG1XVr4+OW7CfoZXKbqcpU00me7Irm7CNI7xjNiOlR8eAlI3XJlWim4stBLactYmMCnGPOI7zWPZ0xgFrmiMYYrpmpCBEBaGvOo5YypXegtlE9qrg4/jsvey8KE1nXXtwFMEgZJx28ePEy1wQnr5++SMSgyKsAPEVFrB1rVkJPRrLUE54cX8aY5sRalKf8d8scoHSw8KDtsQ1zMX9X3MwhhP9RBlVEVJBEvOwqtD5CZZvlLLbQ1RgJ7zpqXmNQfi7/VKvy/xWn2lcVf0phXTP9vw2TMQEbY0KtIMPgwM7XTur3QdxNxkwCvmvAyHMnjm0GXpjuAmRlouIPJhFXQ57OOJg9u9dpbE9K3JJU0OM/aP/p+3IbSXxXh15zMAo0rK0aIaoi8lnDD6E6tOg0P2RF3CtOlwiCdto7SiaK9OGY7dXFVOA3GjssflM8Pp3qU8IpozRL4PQAtzicDhdQw5x/yr3m9q239kH2U+7bN6ZwZpRwWMdzf3KlNb1ZszKTwIe5xlWRvVkaphLB1BN2dZPLkMMUgHWVIqf1hjwE1B+E9ICape+dCzb8dl7V9w+GIg/6LfNQnqY6zaEOsjbxIAjhCVXLY99VFHNq50PAAbfGY6YSdNVyY0K6M93I0C6rvJU3OrBf3oPyRGNLZaZoyPyHdUf0Ba+Clo53Sxj7GojJ76iyRNEfuzkcJS5Qg76rn7LSvyMnZ0aiQ=
  template:
    metadata:
      name: cloudflared-token
      namespace: cloudflare-tunnel-dev
