apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudflare-tunnel-dev

resources:
  - ../../base
  - cloudflared-token-sealedsecret.yaml

patches:
  - target:
      kind: ConfigMap
      name: cloudflared-config
    patch: |-
      - op: replace
        path: /data/config.yaml
        value: |
          tunnel: ce21635c-1779-46cc-9f7d-01fbeac17a21
          metrics: 0.0.0.0:2000

          ingress:
          - hostname: dev.ui.diocesanvitality.org
            service: http://diocesan-vitality-ui.default.svc.cluster.local:80
          - hostname: dev.api.diocesanvitality.org
            service: http://diocesan-vitality-api.default.svc.cluster.local:8000
          - hostname: dev.argocd.diocesanvitality.org
            service: http://argocd-server.argocd.svc.cluster.local:80
          - service: http_status:404

commonLabels:
  environment: development
