apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudflare-tunnel-dev

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: cloudflared
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args
        value:
          - tunnel
          - --config
          - /etc/cloudflared/config/config.yaml
          - --metrics
          - 0.0.0.0:2000
          - run
          - 52a38d40-b4ea-4c13-a32a-5b98507c1015

  - target:
      kind: ConfigMap
      name: cloudflared-config
    patch: |-
      - op: replace
        path: /data/config.yaml
        value: |
          tunnel: 52a38d40-b4ea-4c13-a32a-5b98507c1015
          credentials-file: /etc/cloudflared/creds/credentials.json
          metrics: 0.0.0.0:2000

          ingress:
          - hostname: dev.ui.diocesan-vitality.org
            service: http://diocesan-vitality-ui.default.svc.cluster.local:80
          - hostname: dev.api.diocesan-vitality.org
            service: http://diocesan-vitality-api.default.svc.cluster.local:8000
          - hostname: dev.argocd.diocesan-vitality.org
            service: https://argocd-server.argocd.svc.cluster.local:443
            originRequest:
              noTLSVerify: true
          - service: http_status:404

commonLabels:
  environment: development
