apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudflare-tunnel-dev

resources:
  - ../../base
  - sealedsecret.yaml

patches:
  - target:
      kind: Deployment
      name: cloudflared
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: cloudflare/cloudflared:2024.6.1
      - op: replace
        path: /spec/template/spec/containers/0/args
        value:
          - tunnel
          - --config
          - /etc/cloudflared/config/config.yaml
          - --metrics
          - 0.0.0.0:2000
          - run
          - da4b9224-567a-4ba1-b1b3-9c4eceddfa1e

  - target:
      kind: ConfigMap
      name: cloudflared-config
    patch: |-
      - op: replace
        path: /data/config.yaml
        value: |
          tunnel: da4b9224-567a-4ba1-b1b3-9c4eceddfa1e
          credentials-file: /etc/cloudflared/creds/credentials.json
          metrics: 0.0.0.0:2000

          ingress:
          - hostname: dev.ui.diocesanvitality.org
            service: http://diocesan-vitality-ui.default.svc.cluster.local:80
          - hostname: dev.api.diocesanvitality.org
            service: http://diocesan-vitality-api.default.svc.cluster.local:8000
          - hostname: dev.argocd.diocesanvitality.org
            service: https://argocd-server.argocd.svc.cluster.local:443
            originRequest:
              noTLSVerify: true
          - service: http_status:404

commonLabels:
  environment: development
