---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-credentials
  namespace: cloudflare-tunnel-dev
spec:
  encryptedData:
    credentials.json: AgC0hDI+eC6JBa7lObTJ/JWQON62QJRa4sK95xMPxRR5rTPXPewDUEV3ezv1QPTPQPyhkrxqWk81FqwSn0IAlO1PpTtRKl0EdUglQdkiJNEC6evNGMobuOYnTaOknlYwvi/FJKIzUYxs+1vcoo09y6D/HwrtoJrYqD6l2vUOVTrZZZMA9axL/VYhQcyaEmzGa5UlCN7gV3Y1Fcx8fwVYl1EOwB0YN0b/dbZP3mY4aFGRW7nurDeHtfEm5SaVWTmduYpfRIcFdHid7u/9fJlP0Rp4KTk36qUCyaLFPSyXB9kDK+seLoAair04IF1hBQE9oEeGyoomkiDQe1T+OLqPLToiKJYURsPzFl397vxf/zPDJthhvT9+fdhJ12l2p41LBZM3zjyFmUPGC2j2k25yC7KDqH8FoLTvAekrjkDiRpRuzL8DaDphRM94SPs5Nd89G2Qe2QQa/P41xxblLxHZ6bUuU59ZJGYr1c4dbKgAWAhdNZMXKWyha0qR1T1LNkT1E4BWiiqfHmP73yDAS6k08TP2c8ijMOAJYO9KSO4aovuoM88ijq0Fn6+FOW98KrjRjctplpKG7Zzc7Ut++hZKBuhPpSqYd+3OsMYuHlbDQDDj4jKXV2qz1gHTF4NsBi7SNwS1aIL9JOPC3ZSxsrkp0T7bs3kgjWPspq9CZMSt+kG+Ddtqvcpe2waJScjo+W6O7u1dmuIBIb8avQKtNVZl30qgj2UuPytj+L0WFfum0813yDTn+LJEqKB2vcTZJjILT9jX6+q/FDVthDcx+7EdTbrVJf8n8Xyr82DT74gqE6WDhAZeM7M5S7zD56GKK/BM8wpnmO7G4kt5Dg0SBPoh20fi969BQdN8s4uoxh8PWdMEUbnx9kYHYNmRGu1d4rUFJZUa9k0rEg==
  template:
    metadata:
      name: cloudflare-tunnel-credentials
      namespace: cloudflare-tunnel-dev
