---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-credentials
  namespace: cloudflare-tunnel-dev
spec:
  encryptedData:
    credentials.json: AgAN5L2Kob9Q8V8cNlxA+iSvJorLtdzSXe3vXe3baW5JwCR9EtYOuak4TaXNk0G340jdzTpLdhSxQwvm0fPAUlEu8NJl3BtbM/RovEjHjEWXLlx29zJFL437jeIy56s32MmLdJGylpDgd26uvxktQqIMxlaN1uRG6EVLVrXUC1Ll0w73nB9X54lpDgPhw0gkdXYoEImzYM59p2d6vylwGVrolcJw0zLBuBoEYwuUiGjasUWvObbGR3N4a536yTm+xktgOvzbvZtF3W92rRsZTa9OzOKWBCGcXwQPlbf2E1zOCpOr1GjyuOUvgfDLtFA0xwIZOO81jUs26ZI7KQV+JFgDi4+dzj5QhnS6Bzfk5ZKJWWh0gwDXYGnoL7440czlJYMQXpV9eccWQRCLCPwqAKtaWm5zlx+ZDZ73WjtyQcPCLARWzu0gqVysfm/hoO1dufu5aICUlTGEdltA/bvs2Pm83JwPP1lIa+vitGWD9+RfFDSQhUq8NwWqo3FtlPinU5vNZFGzHRUUR+ThfxsAbHG4bK8pKtgtxJUJQZLWmcDAh2Zp5zq5V2ds80o+PiwH3ncxbkel4jp7I4Y0b1I6XcflNvalnMG+baSBilPg8jaNSpkVzGnbBRohwjHtzkacuJ5tMt6E2HHXcm5PGPE4fbjEdYfGOEc74CT/nurPY1U2ScMp0SHDBrh2CcCfPxOAAqVQhJ8M1i/t56WIirEJBTELZyibtnmPi140iZvX62OonViFJlOOnZXDn76M/Tk0mtaFH6lz1AzDNavknvmB/iSaxodKqa08649reMA0SSPb6sYc5xH5eawt91gsENLAx6BddyXAlpt8PSae/Y1uquGnVre+zzgmc2LN6SZ6dkin3chpHiBaeTN2bCC1f+GHGubido/V75DyFNLWARZY3s8EVT43/hq8/FItf+6jJXFoLzBAHlqq
  template:
    metadata:
      name: cloudflare-tunnel-credentials
      namespace: cloudflare-tunnel-dev
