apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudflare-tunnel-stg

resources:
  - ../../base
  - cloudflared-token-sealedsecret.yaml

patches:
  - target:
      kind: Deployment
      name: cloudflared
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: ConfigMap
      name: cloudflared-config
    patch: |-
      - op: replace
        path: /data/config.yaml
        value: |
          tunnel: stg-tunnel-id-placeholder
          metrics: 0.0.0.0:2000

          ingress:
          - hostname: stg.ui.diocesanvitality.org
            service: http://diocesan-vitality-ui.default.svc.cluster.local:80
            originRequest:
              httpHostHeader: stg.ui.diocesanvitality.org
              noTLSVerify: true
          - hostname: stg.api.diocesanvitality.org
            service: http://diocesan-vitality-api.default.svc.cluster.local:8000
            originRequest:
              httpHostHeader: stg.api.diocesanvitality.org
              noTLSVerify: true
          - hostname: stg.argocd.diocesanvitality.org
            service: https://argocd-server.argocd.svc.cluster.local:443
            originRequest:
              httpHostHeader: stg.argocd.diocesanvitality.org
              noTLSVerify: true
          - service: http_status:404

commonLabels:
  environment: staging
