apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudflare-tunnel-stg

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: cloudflared
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2

commonLabels:
  environment: staging
  - cloudflared-token-sealedsecret.yaml
