apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflare-tunnel
data:
  config.yaml: |
    # Dev Tunnel Configuration
    tunnel: 940349eb-b44f-4125-9308-fa4eb712963a  # optinosis-cluster-dev
    # credentials-file: /etc/cloudflared/credentials.json
    
    # Logging configuration
    loglevel: debug
    
    # Protocol settings
    protocol: quic
    compression: true
    
    # Service connectivity settings
    no-tls-verify: true
    
    # Retry settings
    retries: 10
    grace-period: 30s
    
    # Metrics configuration
    metrics: 0.0.0.0:2000
    
    # Proxy Settings
    proxy-connect-timeout: 30s
    proxy-tls-timeout: 30s
    
    # Dev-specific ingress rules
    ingress:
      # ArgoCD UI - Dev
      - hostname: argocd-optinosis-dev.optinosis.tech
        service: http://argocd-server.argocd.svc.cluster.local:80
        originRequest:
          noTLSVerify: true
          connectTimeout: 30s
          keepAliveConnections: 100
          keepAliveTimeout: 30s
      
      # Kubeflow UI - Dev
      - hostname: kubeflow.optinosis.tech
        service: http://istio-ingressgateway.istio-system.svc.cluster.local:80
        originRequest:
          noTLSVerify: true
          connectTimeout: 30s
          keepAliveConnections: 100
          keepAliveTimeout: 30s
          httpHostHeader: kubeflow.optinosis.tech
          proxyHostHeader: kubeflow.optinosis.tech
          headers:
            Host: [kubeflow.optinosis.tech]
            X-Forwarded-Proto: [https]
            X-Forwarded-Host: [kubeflow.optinosis.tech]
      
      # Open WebUI - Dev  
      - hostname: optinexus2.optinosis.tech
        service: http://open-webui.open-webui.svc.cluster.local:8080
        originRequest:
          noTLSVerify: true
          connectTimeout: 30s
          keepAliveConnections: 100
          keepAliveTimeout: 30s
      
      # Default fallback
      - service: http_status:404