apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: cloudflare-tunnel
spec:
  replicas: 1  # Single replica for dev environment
  template:
    spec:
      containers:
      - name: cloudflared
        resources:
          requests:
            cpu: 10m       # Ultra-minimal CPU - cloudflared is very efficient
            memory: 64Mi   # Reduced memory - sufficient for tunnel operation
          limits:
            cpu: 100m      # Lower limit - prevents resource hogging
            memory: 128Mi  # Lower limit - adequate for dev workload