apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: cloudflare-tunnel
spec:
  selector:
    matchLabels:
      app: cloudflared
  replicas: 1  # Reduced from 2 for better resource efficiency
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: cloudflared
      annotations:
        # This annotation prevents Kubernetes from killing the pod during termination
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    spec:
      terminationGracePeriodSeconds: 120
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:2025.4.0
          args:
            - "tunnel"
            - "--config"
            - "/etc/cloudflared/config.yaml"
            - "run"
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflared-token
                  key: tunnel-token
            # Connection settings
            - name: TUNNEL_TRANSPORT_PROTOCOL
              value: "quic"
            - name: TUNNEL_RETRIES
              value: "10"
            - name: TUNNEL_GRACE_PERIOD
              value: "30s"
            # Origin settings
            - name: TUNNEL_ORIGIN_CERT
              value: "false"
            - name: TUNNEL_METRICS
              value: "0.0.0.0:2000"
          livenessProbe:
            httpGet:
              path: /ready
              port: 2000
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 2000
            failureThreshold: 10
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
          startupProbe:
            httpGet:
              path: /ready
              port: 2000
            failureThreshold: 30
            periodSeconds: 10
          securityContext:
            capabilities:
              add:
                - NET_RAW  # For ICMP proxy functionality
          resources:
            limits:
              cpu: 200m      # Reduced from 500m
              memory: 256Mi  # Reduced from 512Mi
            requests:
              cpu: 50m       # Reduced from 200m
              memory: 128Mi  # Reduced from 256Mi
          volumeMounts:
            - name: config
              mountPath: /etc/cloudflared/
      volumes:
        - name: config
          configMap:
            name: cloudflared-config