apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: cloudflare-tunnel
spec:
  selector:
    matchLabels:
      app: cloudflared
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: cloudflared
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    spec:
      terminationGracePeriodSeconds: 120
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:2025.1.0
          args:
            - "tunnel"
            - "--no-autoupdate"
            - "run"
            - "--token"
            - "$(TUNNEL_TOKEN)"
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflared-token
                  key: tunnel-token
            - name: TUNNEL_METRICS
              value: "0.0.0.0:2000"
          livenessProbe:
            httpGet:
              path: /ready
              port: 2000
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 2000
            failureThreshold: 10
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
          startupProbe:
            httpGet:
              path: /ready
              port: 2000
            failureThreshold: 30
            periodSeconds: 10
          securityContext:
            capabilities:
              add:
                - NET_RAW
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
          # No volume mounts needed - configuration comes from Cloudflare dashboard