apiVersion: v1
kind: Service
metadata:
  name: cloudflared
  namespace: cloudflare-tunnel
spec:
  selector:
    app: cloudflared
  ports:
    - name: metrics
      port: 2000
      targetPort: 2000
  type: ClusterIP
