apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-token
  namespace: cloudflare-tunnel
type: Opaque
stringData:
  # Replace this with your actual Cloudflare tunnel token
  tunnel-token: "your-cloudflare-tunnel-token"