apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  template:
    spec:
      containers:
        - name: backend
          env:
            - name: ENVIRONMENT
              value: "development"
            - name: DEBUG
              value: "true"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  template:
    spec:
      containers:
        - name: frontend
          env:
            - name: NAMESPACE
              value: "diocesan-vitality-dev"
            - name: REACT_APP_ENVIRONMENT
              value: "development"
            - name: REACT_APP_API_URL
              value: "https://devapi.diocesanvitality.org"
            - name: REACT_APP_DEBUG
              value: "true"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline-deployment
spec:
  template:
    spec:
      containers:
        - name: pipeline
          env:
            - name: ENVIRONMENT
              value: "development"
            - name: DEBUG
              value: "true"
            - name: LOG_LEVEL
              value: "DEBUG"
            - name: WORKER_TYPE
              value: "schedule"
          resources:
            requests:
              memory: "1536Mi"
              cpu: "600m"
            limits:
              memory: "2048Mi"
              cpu: "1000m"
