apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  template:
    spec:
      containers:
        - name: backend
          env:
            - name: ENVIRONMENT
              value: "development"
            - name: DEBUG
              value: "true"
          resources:
            requests:
              memory: "80Mi"
              cpu: "50m"
            limits:
              memory: "160Mi"
              cpu: "200m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  template:
    spec:
      containers:
        - name: frontend
          env:
            - name: NAMESPACE
              value: "diocesan-vitality-dev"
            - name: REACT_APP_ENVIRONMENT
              value: "development"
            - name: REACT_APP_API_URL
              value: "https://devapi.diocesanvitality.org"
            - name: REACT_APP_DEBUG
              value: "true"
          resources:
            requests:
              memory: "46Mi"
              cpu: "25m"
            limits:
              memory: "92Mi"
              cpu: "75m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline-discovery-deployment
spec:
  template:
    spec:
      containers:
        - name: pipeline
          env:
            - name: ENVIRONMENT
              value: "development"
            - name: DEBUG
              value: "true"
            - name: LOG_LEVEL
              value: "DEBUG"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline-extraction-deployment
spec:
  replicas: 1 # Dev: reduce to 1 replica
  template:
    spec:
      containers:
        - name: pipeline
          env:
            - name: ENVIRONMENT
              value: "development"
            - name: DEBUG
              value: "true"
            - name: LOG_LEVEL
              value: "DEBUG"
          resources:
            requests:
              memory: "1.5Gi" # Dev: slightly reduced
              cpu: "600m"
            limits:
              memory: "3Gi"
              cpu: "1200m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline-schedule-deployment
spec:
  template:
    spec:
      containers:
        - name: pipeline
          env:
            - name: ENVIRONMENT
              value: "development"
            - name: DEBUG
              value: "true"
            - name: LOG_LEVEL
              value: "DEBUG"
