apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  template:
    spec:
      containers:
        - name: backend
          env:
            - name: ENVIRONMENT
              value: "development"
            - name: DATABASE_URL
              value: "${DEV_DATABASE_URL}"
            - name: SUPABASE_URL
              value: "${DEV_SUPABASE_URL}"
            - name: SUPABASE_KEY
              value: "${DEV_SUPABASE_KEY}"
            - name: DEBUG
              value: "true"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  template:
    spec:
      containers:
        - name: frontend
          env:
            - name: REACT_APP_ENVIRONMENT
              value: "development"
            - name: REACT_APP_API_URL
              value: "https://devapi.diocesanvitality.org"
            - name: REACT_APP_DEBUG
              value: "true"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline-deployment
spec:
  template:
    spec:
      containers:
        - name: pipeline
          env:
            - name: ENVIRONMENT
              value: "development"
            - name: DATABASE_URL
              value: "${DEV_DATABASE_URL}"
            - name: SUPABASE_URL
              value: "${DEV_SUPABASE_URL}"
            - name: SUPABASE_KEY
              value: "${DEV_SUPABASE_KEY}"
            - name: GENAI_API_KEY
              value: "${DEV_GENAI_API_KEY}"
            - name: DEBUG
              value: "true"
            - name: LOG_LEVEL
              value: "DEBUG"
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
