apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: diocesan-vitality-dev

resources:
- ../../application/base
- namespace.yaml
- diocesan-vitality-secrets-sealedsecret.yaml

patches:
- path: development-patches.yaml

# Images - updated automatically by CI/CD pipeline
images:
- name: tomatl/diocesan-vitality:backend
  newName: tomatl/diocesan-vitality
  newTag: development-backend-2025-10-05-19-47-52
- name: tomatl/diocesan-vitality:frontend
  newName: tomatl/diocesan-vitality
  newTag: development-frontend-2025-10-05-19-47-52
- name: tomatl/diocesan-vitality:pipeline
  newName: tomatl/diocesan-vitality
  newTag: development-pipeline-2025-10-05-19-47-52

commonLabels:
  cluster: do-nyc2-dv-dev
  environment: development

replicas:
- count: 1
  name: backend-deployment
- count: 1
  name: frontend-deployment
- count: 1
  name: pipeline-discovery-deployment
- count: 1
  name: pipeline-extraction-deployment
- count: 1
  name: pipeline-schedule-deployment
