apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: diocesan-vitality-dev

resources:
  - ../../application/base
  - namespace.yaml

patches:
  - path: development-patches.yaml

images:
  - name: tomatl/diocesan-vitality:backend-2025-09-15-20-27-14
    newName: tomatl/diocesan-vitality
    newTag: develop-backend-latest
  - name: tomatl/diocesan-vitality:frontend-2025-09-15-22-17-53
    newName: tomatl/diocesan-vitality
    newTag: develop-frontend-latest
  - name: tomatl/diocesan-vitality:pipeline-2025-09-15-22-58-39
    newName: tomatl/diocesan-vitality
    newTag: develop-pipeline-latest

commonLabels:
  environment: development
  cluster: do-nyc2-dv-dev

replicas:
  - name: backend-deployment
    count: 1
  - name: frontend-deployment
    count: 1
  - name: pipeline-deployment
    count: 1
