apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: diocesan-vitality-dev

resources:
  - ../../application/base
  - namespace.yaml

patches:
  - path: development-patches.yaml

images:
  - name: tomatl/diocesan-vitality
    newTag: develop-latest

commonLabels:
  environment: development
  cluster: do-nyc2-dv-dev

replicas:
  - name: backend-deployment
    count: 1
  - name: frontend-deployment
    count: 1
  - name: pipeline-deployment
    count: 1
