apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: diocesan-vitality-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tomknightatl/diocesan-vitality
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: diocesan-vitality
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true