apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflare-tunnel
data:
  config.yaml: |
    # Arg Tunnel Configuration
    tunnel: 785339b9-7a30-40f0-a70d-e5fb9634d515  # optinosis-cluster-arg
    # credentials-file: /etc/cloudflared/credentials.json
    
    # Logging configuration
    loglevel: debug
    
    # Protocol settings
    protocol: quic
    compression: true
    
    # Service connectivity settings
    no-tls-verify: true
    
    # Retry settings
    retries: 10
    grace-period: 30s
    
    # Metrics configuration
    metrics: 0.0.0.0:2000
    
    # Proxy Settings
    proxy-connect-timeout: 30s
    proxy-tls-timeout: 30s
    
    # Dev-specific ingress rules
    ingress:
      # ArgoCD UI - Arg
      - hostname: argocd.optinosis.tech
        service: http://argocd-server.argocd.svc.cluster.local:80
        originRequest:
          noTLSVerify: true
          connectTimeout: 30s
          keepAliveConnections: 100
          keepAliveTimeout: 30s

      # Default fallback
      - service: http_status:404