apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: cloudflare-tunnel
spec:
  replicas: 1  # Single replica due to severe resource constraints
  template:
    spec:
      containers:
      - name: cloudflared
        resources:
          # No requests - allows pod to be scheduled without reserving resources
          limits:
            cpu: 100m      # Still limit to prevent resource hogging
            memory: 128Mi  # Still limit to prevent resource hogging