apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-credentials
type: Opaque
data:
  # This should be replaced with actual sealed secret or managed externally
  # credentials.json: <base64-encoded-tunnel-credentials>
  credentials.json: e30K # Empty JSON object as placeholder
