apiVersion: v1
kind: Service
metadata:
  name: cloudflared-metrics
spec:
  selector:
    app: cloudflared
  ports:
  - name: metrics
    port: 2000
    targetPort: 2000
    protocol: TCP
  type: ClusterIP
