apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: usccb-applicationset
  namespace: argocd # Assuming ArgoCD is installed in the 'argocd' namespace
spec:
  generators:
  - list:
      elements:
      - name: usccb-app
        path: k8s
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/tomknightatl/USCCB # Replace with your repository URL
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: USCCB
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
