apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: diocesan-vitality
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: default
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: doks.digitalocean.com/node-pool
                operator: In
                values:
                - slow-pool
      containers:
      - name: backend
        # IMPORTANT: Replace YOUR_DOCKERHUB_USERNAME with your actual Docker Hub username
        # Using single repository with tags: usccb:backend
        image: tomatl/diocesan-vitality:backend
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "64Mi"
            cpu: "5m"
          limits:
            memory: "128Mi"
            cpu: "25m"
        env:
        # It is strongly recommended to manage secrets using Kubernetes Secrets.
        # 1. Create a secret like this:
        #    kubectl create secret generic supabase-credentials \
        #      --from-literal=SUPABASE_URL='your_supabase_url' \
        #      --from-literal=SUPABASE_KEY='your_supabase_key'
        # 2. Uncomment the envFrom block below.
        envFrom:
        - secretRef:
            name: diocesan-vitality-secrets