apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      serviceAccountName: default
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: frontend
        # IMPORTANT: Replace this with the actual path to your container image
        image: ghcr.io/tomknightatl/usccb/usccb-frontend:v1.0.10
        imagePullPolicy: Always
        ports:
        - containerPort: 80
