apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: usccb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      serviceAccountName: default
      # Comment out or remove imagePullSecrets if using public Docker Hub repositories
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: frontend
        # IMPORTANT: Replace YOUR_DOCKERHUB_USERNAME with your actual Docker Hub username
        # Using single repository with tags: usccb:frontend
        image: tomatl/usccb:frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "32Mi"
            cpu: "5m"
          limits:
            memory: "64Mi"
            cpu: "10m"