apiVersion: batch/v1
kind: CronJob
metadata:
  name: usccb-pipeline-cronjob
  namespace: usccb
spec:
  # Run daily at 2 AM UTC
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: pipeline
            image: $DOCKER_USERNAME/usccb:pipeline
            imagePullPolicy: Always
            resources:
              requests:
                memory: "200Mi"
                cpu: "50m"
              limits:
                memory: "300Mi"
                cpu: "100m"
            env:
            - name: SUPABASE_URL
              valueFrom:
                secretKeyRef:
                  name: usccb-secrets
                  key: supabase-url
            - name: SUPABASE_KEY
              valueFrom:
                secretKeyRef:
                  name: usccb-secrets
                  key: supabase-key
            - name: GENAI_API_KEY_USCCB
              valueFrom:
                secretKeyRef:
                  name: usccb-secrets
                  key: genai-api-key
            - name: SEARCH_API_KEY_USCCB
              valueFrom:
                secretKeyRef:
                  name: usccb-secrets
                  key: search-api-key
            - name: SEARCH_CX_USCCB
              valueFrom:
                secretKeyRef:
                  name: usccb-secrets
                  key: search-cx
            volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: chrome-user-data
              mountPath: /app/.chrome-user-data
          volumes:
          - name: tmp
            emptyDir: {}
          - name: chrome-user-data
            emptyDir: {}
          restartPolicy: OnFailure
      backoffLimit: 2
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1