apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline-deployment
  namespace: diocesan-vitality
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: pipeline
  template:
    metadata:
      labels:
        app: pipeline
    spec:
      serviceAccountName: default
      nodeSelector:
        doks.digitalocean.com/node-pool: fast-pool
      containers:
      - name: pipeline
        image: tomatl/diocesan-vitality:pipeline
        imagePullPolicy: Always
        resources:
          requests:
            memory: "512Mi"
            cpu: "100m"
          limits:
            memory: "2Gi"
            cpu: "1500m"
        env:
        - name: SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: diocesan-vitality-secrets
              key: supabase-url
        - name: SUPABASE_KEY
          valueFrom:
            secretKeyRef:
              name: diocesan-vitality-secrets
              key: supabase-key
        - name: GENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: diocesan-vitality-secrets
              key: genai-api-key
        - name: SEARCH_API_KEY
          valueFrom:
            secretKeyRef:
              name: diocesan-vitality-secrets
              key: search-api-key
        - name: SEARCH_CX
          valueFrom:
            secretKeyRef:
              name: diocesan-vitality-secrets
              key: search-cx
        - name: MPLCONFIGDIR
          value: "/tmp/matplotlib"
        - name: HOME
          value: "/tmp"
        - name: WDM_LOCAL_CACHE
          value: "/tmp/webdriver-cache"
        # Command line arguments for specific processing
        command: ["python", "run_pipeline.py"]
        args:
        - "--max_parishes_per_diocese"
        - "50"
        - "--num_parishes_for_schedule"
        - "101"
        - "--monitoring_url"
        - "http://backend-service:8000"
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: chrome-user-data
          mountPath: /app/.chrome-user-data
      volumes:
      - name: tmp
        emptyDir: {}
      - name: chrome-user-data
        emptyDir: {}
      restartPolicy: Always