name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug! Please fill out this template to help us understand and reproduce the issue.

  - type: checkboxes
    id: search
    attributes:
      label: Search for existing issues
      description: Please search existing issues to avoid duplicates
      options:
        - label: I have searched for existing issues and this is not a duplicate
          required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the system is affected?
      options:
        - Pipeline (Data Extraction)
        - Backend API
        - Frontend Dashboard
        - Database/Storage
        - Deployment/Infrastructure
        - Documentation
        - Testing
        - Other
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where did this issue occur?
      options:
        - Local Development
        - Development Cluster
        - Staging
        - Production
        - CI/CD Pipeline
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Please provide detailed steps to reproduce the issue
      placeholder: |
        1. Go to '...'
        2. Run command '...'
        3. See error '...'
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened instead
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs/Output
      description: Please include any relevant error messages, logs, or screenshots
      placeholder: |
        ```
        Paste error logs here
        ```
    validations:
      required: false

  - type: textarea
    id: system_info
    attributes:
      label: System Information
      description: Please provide relevant system information
      placeholder: |
        - OS: [e.g., Ubuntu 22.04, Windows 11, macOS 14]
        - Python Version: [e.g., 3.12.0]
        - Node.js Version: [e.g., 20.9.0]
        - Docker Version: [e.g., 24.0.6]
        - Browser: [e.g., Chrome 118, Firefox 119] (if frontend issue)
        - Architecture: [e.g., x86_64, arm64]
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: |
        - Configuration details
        - Recent changes made
        - Workarounds tried
        - Related issues or PRs
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to contribute to fixing this issue?
      options:
        - label: I would be willing to submit a PR to fix this issue
          required: false