name: ❓ Question
description: Ask a question about the project
title: "[Question]: "
labels: ["question", "needs triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for your question! Please fill out this template to help us provide the best answer.

  - type: checkboxes
    id: search
    attributes:
      label: Search existing resources
      description: Please check existing resources before asking
      options:
        - label: I have searched existing issues and discussions
          required: true
        - label: I have checked the documentation
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What is your question about?
      options:
        - Getting Started/Setup
        - Usage/How-to
        - Configuration
        - Troubleshooting
        - Performance
        - Security
        - Development/Contributing
        - Deployment
        - Data/Output
        - Architecture/Design
        - Best Practices
        - Other
    validations:
      required: true

  - type: dropdown
    id: audience
    attributes:
      label: Audience
      description: What describes you best?
      options:
        - New User
        - Regular User
        - Developer/Contributor
        - System Administrator
        - Researcher
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: Please ask your question clearly and provide context
      placeholder: |
        What would you like to know?

        Provide as much context as possible:
        - What are you trying to accomplish?
        - What have you tried so far?
        - What specific information do you need?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context and Background
      description: Provide additional context that might help us answer your question
      placeholder: |
        - Your use case or goal
        - Current setup or environment
        - Previous experience with similar tools
        - Specific constraints or requirements
    validations:
      required: false

  - type: textarea
    id: attempted
    attributes:
      label: What Have You Tried?
      description: What steps have you already taken to find the answer?
      placeholder: |
        - Documentation sections you've read
        - Commands or configurations you've tried
        - Error messages you've encountered
        - Resources you've consulted
    validations:
      required: false

  - type: textarea
    id: system_info
    attributes:
      label: System Information (if relevant)
      description: Provide system details if they might be relevant to your question
      placeholder: |
        - OS: [e.g., Ubuntu 22.04, Windows 11, macOS 14]
        - Python Version: [e.g., 3.12.0]
        - Installation method: [e.g., from source, Docker, pip]
        - Environment: [e.g., local, cloud, cluster]
    validations:
      required: false

  - type: dropdown
    id: urgency
    attributes:
      label: Urgency
      description: How urgent is getting an answer to this question?
      options:
        - Low - Just curious
        - Medium - Would help my project
        - High - Blocking my work
        - Critical - Production issue
    validations:
      required: true

  - type: textarea
    id: additional_info
    attributes:
      label: Additional Information
      description: Anything else that might help us answer your question?
      placeholder: |
        - Links to relevant documentation
        - Screenshots or logs (if applicable)
        - Related issues or discussions
        - Specific deadline or timeline
    validations:
      required: false

  - type: checkboxes
    id: follow_up
    attributes:
      label: Follow-up Actions
      description: How can you help improve the project based on this question?
      options:
        - label: I would be willing to contribute documentation improvements
          required: false
        - label: I could help answer similar questions from other users
          required: false
        - label: I would be interested in contributing code improvements
          required: false
