apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: charts-pvc
spec:
  accessModes:
    - ReadWriteMany  # Multiple pods can read/write
  resources:
    requests:
      storage: 1Gi  # Small size, just for chart images
  storageClassName: do-block-storage
