# Sealed Secrets configuration for production environment
fullnameOverride: sealed-secrets-controller

# Production-specific settings
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

# Enable metrics for monitoring
metrics:
  serviceMonitor:
    enabled: true

# Production logging
logLevel: warn

# Security context
securityContext:
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65534

# Pod security context
podSecurityContext:
  fsGroup: 65534

# Service configuration
service:
  type: ClusterIP
  port: 8080

# High availability for production
replicaCount: 3

# Pod disruption budget
podDisruptionBudget:
  enabled: true
  minAvailable: 2

# Additional labels
commonLabels:
  environment: production
  component: sealed-secrets
