apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cloudflare-tunnel-prd
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          environment: prd
  template:
    metadata:
      name: 'cloudflare-tunnel-prd'
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "1"
    spec:
      project: default
      source:
        repoURL: https://github.com/tomknightatl/diocesan-vitality
        targetRevision: HEAD
        path: k8s/infrastructure/cloudflare-tunnel/environments/prd
      destination:
        server: "{{server}}"
        namespace: "cloudflare-tunnel"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
      ignoreDifferences:
      - group: ""
        kind: Secret
        jsonPointers:
        - /data
