apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cloudflare-tunnel-multi-env
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
          environment: dev
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
          environment: stg
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
          environment: prd
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
          environment: arg
  template:
    metadata:
      name: 'cloudflare-tunnel-{{name}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/tomknightatl/infra.git
        targetRevision: HEAD
        path: 'argocd/cloudflare-tunnel/overlays/{{metadata.labels.environment}}'
      destination:
        server: '{{server}}'
        namespace: cloudflare-tunnel
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true