apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: metrics-server-multi-env
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
        matchExpressions:
        - key: environment
          operator: In
          values: ["dev", "stg", "prd", "arg", "kub"]
      values:
        environment: '{{metadata.labels.environment}}'
  template:
    metadata:
      name: 'metrics-server-{{name}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://kubernetes-sigs.github.io/metrics-server/
        chart: metrics-server
        targetRevision: "3.12.1"
        helm:
          parameters:
          - name: args
            value: "{--cert-dir=/tmp,--secure-port=4443,--kubelet-preferred-address-types=InternalIP\\,ExternalIP\\,Hostname,--kubelet-use-node-status-port,--metric-resolution=15s,--kubelet-insecure-tls}"
          - name: resources.requests.cpu
            value: "100m"
          - name: resources.requests.memory
            value: "200Mi"
      destination:
        server: '{{server}}'
        namespace: kube-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true