apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-applicationsets-stg
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    environment: stg
    app.kubernetes.io/name: root-applicationsets
    app.kubernetes.io/component: gitops
spec:
  project: default
  source:
    repoURL: https://github.com/tomknightatl/diocesan-vitality
    targetRevision: HEAD
    path: k8s/argocd
    directory:
      include: "*-stg-applicationset.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
  revisionHistoryLimit: 10
