apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sealed-secrets-prd
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          environment: prd
  template:
    metadata:
      name: 'sealed-secrets-prd'
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "0"
    spec:
      project: default
      sources:
      - repoURL: https://bitnami-labs.github.io/sealed-secrets
        chart: sealed-secrets
        targetRevision: "2.17.0"
        helm:
          valueFiles:
            - $values/k8s/infrastructure/sealed-secrets/values-prd.yaml
      - repoURL: https://github.com/tomknightatl/diocesan-vitality
        targetRevision: HEAD
        ref: values
      destination:
        server: "{{server}}"
        namespace: "kube-system"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
        - Replace=true
