apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: usccb-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tomknightatl/USCCB
    targetRevision: develop
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: usccb-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true