apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: usccb-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/tomknightatl/USCCB
    targetRevision: develop  # Track develop branch for dev environment
    path: k8s
    
  destination:
    server: https://kubernetes.default.svc
    namespace: usccb-dev
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
        
  revisionHistoryLimit: 10