apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: usccb-pipeline
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/tomknightatl/USCCB
    targetRevision: HEAD
    path: k8s
    directory:
      include: pipeline-*
  destination:
    server: https://kubernetes.default.svc
    namespace: usccb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10