apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: cloudflare-tunnel
spec:
  replicas: 2  # Higher availability for stg
  template:
    spec:
      containers:
      - name: cloudflared
        resources:
          requests:
            cpu: 100m      # Moderate CPU for stg
            memory: 256Mi  # Moderate memory for stg
          limits:
            cpu: 500m      # Higher limit for stg
            memory: 512Mi  # Higher limit for stg