---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared-token
  namespace: cloudflare-tunnel
spec:
  encryptedData:
    tunnel-token: AgAGidaWIWD6MV+xAb9w8uI2cIjYuIqU9FO/zP2rRU70R8Rw0rWsys7Q734Tvd+lF0IGtptb0AaFsPF9vDnbp1g2UNLxHijN0bNuPoPE8zeqOMErMkZo+sZk7YK3uo9BWDQ8UvIAGuFc+eI7Lo0kjQyLV7FbMQndnx5NJHaw5raaBJyUekNG3bKt7vz9ZA4V4/xkKhOPuET/elNRqtJg+stHFOfsDZ6vFqqrpVxzRy8NkMIPOOIVIGe1RkUI9dxbfd8NgdEWFTeMarmgykO0Nj1z+DbA2RVCJZau/i+LGbP50E0zb0xSRoXqJDl8CKyA6+7JDrRYo+cPeD524dMlfC99nnjGMOfUWwhA2x45aPqrNhxm1nyIoJAGjnrZHodUzdHUCOt/d1Lk9capI4/UwCNbs038MHGjBgIAMsRHSLv3oEroQgPK2e/nld3WQ300yUgquR2K/D/8N0wOysTvzHZ9NO2XBSGp5st3rU4cj+82C6GdJP3RzIRYs94ukyg9rSvqS3xWATqHkiJcGVr+Wc5EtiZ8abgW/WzZz1i6ti1kbPpWwzYZJecdhuQoOxKuozILJSDcK40Le1g+YvZ7w7q/hXRr2BRBfDbhvS7imQeOug8q3u9R38bMUs061MY8zvNHl+k8r8x+/863onfGaZ7MjsHDmEdfb86UZip0kQ7GMNhaeUfxfq3N6/wwS+dkREj31qiv8LlSNHe/zAPaPAba2cFxacBCyAW/iJTD7JmPaocO8pOxbcSdFikHPy5gYW8YIkBLAj2tfuxMriiREMYH5MoaaMZqLl0zV3D+U83MZ3gUTuha5wWryrjXUIpp3+649/ry/1PHfwoGw5ER/kEYd3y2NlNo2X0mIBMFqSYAxTVBZRVCfL+PtYhhWBeJDDRHmuYDm+l7xwsbWjtNVRZAcurEbiYxwEBMk+Z/1MWN2vvES91KW6sdfw==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflared-token
      namespace: cloudflare-tunnel
