apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflare-tunnel
data:
  config.yaml: |
    # Prd Tunnel Configuration
    tunnel: bab0b2da-d805-491c-be12-81f60c3db991  # optinosis-cluster-prd
    # credentials-file: /etc/cloudflared/credentials.json
    
    # Logging configuration
    loglevel: warn
    
    # Protocol settings
    protocol: quic
    compression: true
    
    # Service connectivity settings
    no-tls-verify: true
    
    # Retry settings
    retries: 10
    grace-period: 30s
    
    # Metrics configuration
    metrics: 0.0.0.0:2000
    
    # Proxy Settings
    proxy-connect-timeout: 60s
    proxy-tls-timeout: 60s
    
    # Prd-specific ingress rules
    ingress:
      # Open WebUI - Prd (clean hostname for production)
      - hostname: optinexus2.optinosis.tech   # This will become optinexus.optinosis.tech
        service: http://open-webui.open-webui.svc.cluster.local:8080
        originRequest:
          noTLSVerify: true
          connectTimeout: 30s
          keepAliveConnections: 200
          keepAliveTimeout: 60s
      
      # Default fallback
      - service: http_status:404