apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudflare-tunnel

resources:
  - ../../base
  - sealedsecret.yaml

patches:
  - path: resource-limits.yaml
    target:
      kind: Deployment
      name: cloudflared