apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: usccb-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        environment: dev
    spec:
      serviceAccountName: default
      # Comment out or remove imagePullSecrets if using public Docker Hub repositories
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: backend
        image: tomatl/usccb:backend-develop
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: ENVIRONMENT
          value: "development"
        envFrom:
        - secretRef:
            name: supabase-credentials