-- Create DioceseParishDirectoryOverride table
-- This table allows manual overrides for parish directory URLs when the automated discovery is incorrect

-- Create the override table with the same structure as DiocesesParishDirectory
CREATE TABLE IF NOT EXISTS "public"."DioceseParishDirectoryOverride" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "diocese_url" character varying,
    "parish_directory_url" character varying,
    "found" character varying,
    "found_method" character varying,
    "updated_at" character varying,
    "diocese_id" integer
);

-- Set ownership
ALTER TABLE "public"."DioceseParishDirectoryOverride" OWNER TO "postgres";

-- Add auto-increment primary key
ALTER TABLE "public"."DioceseParishDirectoryOverride" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."DioceseParishDirectoryOverride_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Add primary key constraint
ALTER TABLE ONLY "public"."DioceseParishDirectoryOverride"
    ADD CONSTRAINT "DioceseParishDirectoryOverride_pkey" PRIMARY KEY ("id");

-- Add unique constraint to ensure one override per diocese
ALTER TABLE ONLY "public"."DioceseParishDirectoryOverride"
    ADD CONSTRAINT "unique_override_diocese_id" UNIQUE ("diocese_id");

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS "idx_override_diocese_id" ON "public"."DioceseParishDirectoryOverride" USING "btree" ("diocese_id");
CREATE INDEX IF NOT EXISTS "idx_override_diocese_url" ON "public"."DioceseParishDirectoryOverride" USING "btree" ("diocese_url");

-- Add comments for documentation
COMMENT ON TABLE "public"."DioceseParishDirectoryOverride" IS 'Manual overrides for parish directory URLs when automated discovery needs correction';
COMMENT ON COLUMN "public"."DioceseParishDirectoryOverride"."diocese_url" IS 'Diocese website URL (should match Dioceses.Website)';
COMMENT ON COLUMN "public"."DioceseParishDirectoryOverride"."parish_directory_url" IS 'Override URL for parish directory page';
COMMENT ON COLUMN "public"."DioceseParishDirectoryOverride"."found" IS 'Status or reason for override (e.g., "manual override", "automated failed")';
COMMENT ON COLUMN "public"."DioceseParishDirectoryOverride"."found_method" IS 'Method used to find override URL (e.g., "manual", "support ticket")';
COMMENT ON COLUMN "public"."DioceseParishDirectoryOverride"."diocese_id" IS 'Foreign key reference to Dioceses.id';

-- Enable row level security (matching pattern from original table)
ALTER TABLE "public"."DioceseParishDirectoryOverride" ENABLE ROW LEVEL SECURITY;

-- Create policy for access (matching pattern from original table)
CREATE POLICY "Allow notebook access" ON "public"."DioceseParishDirectoryOverride" USING (true) WITH CHECK (true);

-- Grant permissions (matching pattern from original table)
GRANT ALL ON TABLE "public"."DioceseParishDirectoryOverride" TO "anon";
GRANT ALL ON TABLE "public"."DioceseParishDirectoryOverride" TO "authenticated";
GRANT ALL ON TABLE "public"."DioceseParishDirectoryOverride" TO "service_role";

-- Grant sequence permissions
GRANT ALL ON SEQUENCE "public"."DioceseParishDirectoryOverride_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."DioceseParishDirectoryOverride_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."DioceseParishDirectoryOverride_id_seq" TO "service_role";

-- Sample queries to work with override table:
/*
-- Add an override for a specific diocese
INSERT INTO "public"."DioceseParishDirectoryOverride"
(diocese_id, diocese_url, parish_directory_url, found, found_method, updated_at)
VALUES
(2024, 'https://archatl.com', 'https://archatl.com/parishes-directory', 'manual override', 'manual', NOW()::text);

-- View all overrides
SELECT
    o.diocese_id,
    d.Name as diocese_name,
    o.diocese_url,
    o.parish_directory_url,
    o.found,
    o.found_method,
    o.created_at
FROM "public"."DioceseParishDirectoryOverride" o
LEFT JOIN "public"."Dioceses" d ON o.diocese_id = d.id
ORDER BY o.created_at DESC;

-- Check if a diocese has an override
SELECT * FROM "public"."DioceseParishDirectoryOverride" WHERE diocese_id = 2024;

-- Get parish directory URL with override priority
SELECT
    COALESCE(override.parish_directory_url, original.parish_directory_url) as parish_directory_url,
    CASE
        WHEN override.parish_directory_url IS NOT NULL THEN 'override'
        ELSE 'original'
    END as source
FROM "public"."Dioceses" d
LEFT JOIN "public"."DiocesesParishDirectory" original ON d.id = original.diocese_id
LEFT JOIN "public"."DioceseParishDirectoryOverride" override ON d.id = override.diocese_id
WHERE d.id = 2024;
*/