-- Insert Atlanta parishes into ParishesTestSet table
-- This creates a test dataset of Archdiocese of Atlanta parishes
-- Diocese ID 2024 = Archdiocese of Atlanta

INSERT INTO "public"."ParishesTestSet" ("Name", "Web", diocese_id, diocese_url, extraction_method, extracted_at)
VALUES
('All Saints', 'http://www.allsaintsdunwoody.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Basilica of the Sacred Heart of Jesus', 'http://www.sacredheartatlanta.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Capilla San Juan Diego', NULL, 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Capilla Santo Domingo', NULL, 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Cathedral of Christ the King', 'https://cathedralctk.com/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Christ Our Hope', 'https://christourhopeatl.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Christ Our King and Savior', 'http://www.cokas.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Christ the Redeemer', 'http://www.ctrcc.net/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Church of the Purification of the Blessed Virgin Mary', 'https://www.heritagega.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Corpus Christi', 'http://www.corpuschristicc.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Divine Mercy Mission', 'https://divinemercyatl.com/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Divino Niño Jesús', 'http://www.divinonino.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('El Señor es mi Pastor', NULL, 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Epiphany Byzantine Catholic Church', 'https://epiphanybyz.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Good Samaritan', 'http://goodsamaritanellijay.com/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Good Shepherd', 'http://gsrcc.net/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Holy Cross', 'http://www.holycrossatlanta.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Holy Family Knanaya Syro-Malabar Catholic Church', 'http://www.stthomasdiocese.org/parishes/atlanta-0', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Holy Family', 'http://www.holyfamilycc.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Holy Name of Jesus Chinese Catholic Mission', 'http://www.hnojatl.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Holy Spirit', 'http://www.hsccatl.com/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Holy Trinity', 'http://www.holytrinityptc.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Holy Vietnamese Martyrs', 'http://www.cttdvnatl.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Immaculate Heart of the Blessed Virgin Mary', 'http://www.ihmatlanta.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Kidanemehret Eritrean Geez Rite Catholic Church', 'https://www.kidanemehretatlanta.com/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Korean Martyrs', 'http://kmccga.com/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Mary Our Queen', 'http://www.maryourqueen.com/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Most Blessed Sacrament', 'http://www.mbschurch.com/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Mother of God Byzantine-Ukrainian Catholic Church', 'https://motherofgodchurch.wordpress.com/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Nuestra Señora de las Américas', 'https://www.oloacm.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Our Lady of LaSalette', 'http://www.lasalettecanton.com/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Our Lady of Lourdes', 'http://www.lourdesatlanta.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Our Lady of Perpetual Help', 'http://www.olphcc.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Our Lady of the Assumption', 'http://www.olachurch.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Our Lady of the Mount', 'http://olmcc.com/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Our Lady of the Mountains', 'https://www.olmjasper.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Our Lady of Vietnam', 'http://www.giaoxuducmevietnam.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Prince of Peace', 'http://www.popfb.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Queen of Angels', 'https://qofathomson.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Sacred Heart of Jesus', 'http://www.sacredheartofhartwell.com/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Sacred Heart - Griffin', 'http://www.sacredheartofgriffin.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Sacred Heart - Milledgeville', 'http://www.sacredheartmilledgeville.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Aelred', 'http://www.staelred.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Alphonsa Syro-Malabar Catholic Church', 'https://www.saccatl.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Andrew Kim', 'http://sakc.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Andrew', 'http://www.standrewcatholic.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Ann', 'http://st-ann.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Anna', 'http://www.st-annas.com/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Anthony of Padua', 'http://www.stanthonyatlanta.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Anthony', 'http://www.saintanthonyblueridge.com/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Augustine', 'http://www.staugcc.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Benedict', 'http://www.stbenedict.net/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Bernadette', 'https://www.stbernadettecc.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Brendan the Navigator', 'http://www.stbrendansatl.com/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Brigid', 'http://www.saintbrigid.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Catherine Laboure', 'http://www.stcatherinelabourega.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Catherine of Siena', 'http://www.stcatherinercc.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Clare of Assisi', 'http://stclarecc.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Clement', 'http://www.stclementsga.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Elizabeth Ann Seton', NULL, 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Francis de Sales', 'https://www.fsspatl.com/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Francis of Assisi', 'http://www.saintfrancisofassisi.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Francis of Assisi', 'http://www.stfac.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Gabriel', 'http://www.stgabrielga.com/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint George', 'http://www.stgeorgenewnan.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Gerard Majella', 'http://www.saintgerardmajella.net/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Helena', 'https://sthelenacc-clayton.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint James the Apostle', 'https://stjamesapostlecatholicchurch.com/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint James', 'http://stjamesmadison.catholicparish.info/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint John Chrysostom Melkite', 'http://www.stjohnmelkite.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint John Neumann', 'http://www.sjnlilburn.com/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint John Paul II', 'https://stjohnpauliicatholicchurch.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint John the Evangelist', 'http://www.stjohnevangelist.net/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint John Vianney', 'http://www.sjvpar.net/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Joseph Maronite Catholic Church', 'http://www.sjmcc.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Joseph', 'http://www.stjosephathens.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Joseph', 'http://www.sjccdalton.com/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Joseph', 'http://www.saintjosephcc.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Joseph', 'https://qofathomson.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Jude the Apostle', 'https://judeatl.com/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Katharine Drexel', NULL, 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Lawrence', 'http://www.saintlaw.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Luke the Evangelist', 'http://www.stlukercc.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Margaret of Scotland Catholic Church', 'https://stmargaretofscotland.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Marguerite D''Youville', 'http://www.stmdy.com/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Mark', 'https://stmarkrcc.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Mary Magdalene', 'http://www.smmcatholic.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Mary Mother of God', 'http://www.stmaryjackson.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Mary', 'http://www.smcrome.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Mary', 'http://stmarystoccoa.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Mary', 'https://negacatholic.com/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Matthew', 'http://www.saintmatthew.us/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Matthew', 'http://www.saintmatthewcc.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Michael the Archangel', 'http://www.saintmichaelcc.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Michael', 'http://www.saintmichael.cc/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Monica', 'http://www.saintmonicas.com/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Oliver Plunkett', 'http://www.stolivers.com/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Patrick', 'http://www.stpatricksga.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Paul of the Cross', 'http://www.saintpaulofthecross.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Paul the Apostle', 'http://www.stpaulcleveland.com/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Peter Chanel', 'http://www.stpeterchanel.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Peter the Rock', 'http://www.stpetertherock.com/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Peter', 'https://www.stplagrange.com/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Philip Benizi', 'http://www.stphilipbenizi.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Pius X', 'http://www.spxconyers.com/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Stephen the Martyr', 'http://www.ststephenthemartyr.info/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Theresa of the Child Jesus', 'http://www.sainttheresacatholicchurch.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Thomas Aquinas', 'http://www.sta.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Thomas More', 'http://www.stmgaparish.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Thomas the Apostle', 'https://sttacc.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Toribio Romo', NULL, 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saint Vincent de Paul', 'http://www.saintvincentdepaulchurch.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Saints Peter and Paul', 'https://www.ssppatl.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('San Felipe de Jesus', NULL, 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Shrine of the Immaculate Conception', 'http://www.catholicshrineatlanta.org/', 2024, 'https://archatl.com', 'manual testset', NOW()::text),
('Transfiguration', 'http://www.transfiguration.com/', 2024, 'https://archatl.com', 'manual testset', NOW()::text)
ON CONFLICT (diocese_id, "Name") DO NOTHING;

-- Query to verify the inserts:
-- SELECT COUNT(*) FROM "public"."ParishesTestSet";

-- Query to see all inserted records:
-- SELECT Name, Web FROM "public"."ParishesTestSet" ORDER BY Name;

-- Query to see only parishes with websites:
-- SELECT Name, Web FROM "public"."ParishesTestSet" WHERE Web IS NOT NULL ORDER BY Name;

-- Query to see parishes without websites:
-- SELECT Name FROM "public"."ParishesTestSet" WHERE Web IS NULL ORDER BY Name;
